In [540]:
import numpy as np
import os
import math as mt
from collections import Counter


Using Numpy

In [541]:
a=np.array([4,5,6])
b=np.array([10,20,30])
print(f"Output by + operator : {a+b}")
result=np.concatenate((a,b))
print(f"Concatensted array: {result}")
print(f"testing: {np.sum(b)}")

Output by + operator : [14 25 36]
Concatensted array: [ 4  5  6 10 20 30]
testing: 60


Using List
List can not reshape itself but should be converted to numpy array 
list is slower
list take large memory

In [542]:
list_general=[]
list_a=[4,5,6]
list_b=[10,20,30]

# 1D vs 1D list
print(f"Number of elements: {Counter(list_b)}")
print("1D by 1D list")
print(f"""Lists:
list_a: {list_a}
list_b: {list_b}""")
for i,numA in enumerate(list_a):
    for j,numB in enumerate(list_b):
        if i==j:
            list_general.append(numA+numB)
        else:
            continue
print(f"The broadcast Output: {list_general}")
list_d=[
    [1,2,3],
    [4,5,6]
]
print(f"List:              {list_d}")
print(f"Concatenated List: {list_a+list_b}")
# Two Dimensions list with one dimension list
print()
print("2D list vs 1D list")
list_f=[]
for k, element in enumerate(list_d): # break list 
    # print(f"{k}: {element}")
    list_e=[]
    for l,ind_element in enumerate(element):
        # print(ind_element)
        for m,numC in enumerate(list_b):
            if l==m:
                list_e.append(ind_element+numC)
            else:
                continue
    list_f+=list_e
print(f"The Output by +:     {list_f}")
# Reshaping the shape of list
arr=np.array(list_f)
arr=arr.reshape(2,3)
print(f"""Final Output:      
{arr}""")
# print(list_f)

Number of elements: Counter({10: 1, 20: 1, 30: 1})
1D by 1D list
Lists:
list_a: [4, 5, 6]
list_b: [10, 20, 30]
The broadcast Output: [14, 25, 36]
List:              [[1, 2, 3], [4, 5, 6]]
Concatenated List: [4, 5, 6, 10, 20, 30]

2D list vs 1D list
The Output by +:     [11, 22, 33, 14, 25, 36]
Final Output:      
[[11 22 33]
 [14 25 36]]


Numpy Application

In [543]:
a=np.array([
    [1,2,3],
    [4,5,6]
])
b=np.array([10,20,30])
c=b+a
c.reshape(3,2)
print(f"""Reshaped array: 
{c}""")

Reshaped array: 
[[11 22 33]
 [14 25 36]]


Numpy

In [544]:
a=np.ones(100,dtype=int)
a=a.reshape(10,10)
my_arr=np.arange(2,11)
print(f"Number of elements: {len(my_arr)}")
my_arr=my_arr.reshape(3,3)
# print(np.linspace(1,4,15)) 1 and 4 are start and end number but 515 is number of values to generate
print(my_arr)
array=np.array([
    [3,-3,6],
    [-1,5,2],
    [2,0,3]
])
print(f"Array: {array}\n")
inverse=np.linalg.inv(array) #calculating inverse of matrix
Transporse=np.linalg.matrix_transpose(array)
print(f"""Inverse of matix 
{array} is: 

{inverse}\n""")
print(f"""Transporse of matix 
{array} is: 

{Transporse}""")

Number of elements: 9
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Array: [[ 3 -3  6]
 [-1  5  2]
 [ 2  0  3]]

Inverse of matix 
[[ 3 -3  6]
 [-1  5  2]
 [ 2  0  3]] is: 

[[-0.41666667 -0.25        1.        ]
 [-0.19444444  0.08333333  0.33333333]
 [ 0.27777778  0.16666667 -0.33333333]]

Transporse of matix 
[[ 3 -3  6]
 [-1  5  2]
 [ 2  0  3]] is: 

[[ 3 -1  2]
 [-3  5  0]
 [ 6  2  3]]


Simple task

In [ ]:
data=np.array([
    [65,70,75,80,85],
    [50,55,60,65,70],
    [90,92,94,96,98],
    [40,45,50,55,60],
    [78,82,85,88,90],
    [55,60,65,70,75],
    [88,85,82,80,78],
    [72,74,76,78,80],
    [60,62,64,66,68],
    [95,93,91,89,87]
])
counter=0
#Find the shape of dataset above
print(f"The shape of dataset is: {data.shape}")
#Find the total number of elements like number of student
print(f"Number of elements: {len(data)} elements")
#find total number of marks in the array
for i,element in enumerate(data,start=1):
    for j,ind_element in enumerate(element,start=1):
        counter+=j
print(f"Total number of Elements: {counter}")

#Extract first student
To_Extract=int(input("Enter The Position of Student to extract: "))
student=''
maximum=''
minimum=''
for i,element in enumerate(data,start=1):
    if i==To_Extract:
        student=element
        maximum=np.max(element)
        minimum=np.min(element)
        break
    else:
        continue
print(f"{To_Extract} student's marks are: {student}")
print(f"Maximum marks from selected student: {maximum}")
print(f"Minimum marks from selected student: {minimum}")

# Find minimum and maximum
print(f"General maximum Marks: {np.max(data)}")
print(f"General minimum Marks: {np.min(data)}")

 #Statistical Analysis
print()
print("Statistical Analysis")
print(f"""General Central measure:
Mean: {np.mean(data)}
Median: {round((np.median(data)),4)}
Standard Deviation: {round((np.std(data)),4)}
""")
print("Individual subject Measure of central tendency")
for i,element in enumerate(data,start=1):
    print(f"statistical Analysis for {i} subject:")
    # for j,ind_element in enumerate(element,start=1):
    print(f"""Mean: {np.mean(element)}
Median: {np.median(element)}
Standard Deviation: {round((np.std(element)),4)}\n""")
    

The shape of dataset is: (10, 5)
Number of elements: 10 elements
Total number of Elements: 150
5 student's marks are: [78 82 85 88 90]
Maximum marks from selected student: 90
Minimum marks from selected student: 78
General maximum Marks: 98
General minimum Marks: 40

Statistical Analysis
General Central measure:
Mean: 74.22
Median: 75.5
Standard Deviation: 14.4766

Individual subject Measure of central tendency
statistical Analysis for 1 subject:
Mean: 75.0
Median: 75.0
Standard Deviation: 7.0711

statistical Analysis for 2 subject:
Mean: 60.0
Median: 60.0
Standard Deviation: 7.0711

statistical Analysis for 3 subject:
Mean: 94.0
Median: 94.0
Standard Deviation: 2.8284

statistical Analysis for 4 subject:
Mean: 50.0
Median: 50.0
Standard Deviation: 7.0711

statistical Analysis for 5 subject:
Mean: 84.6
Median: 85.0
Standard Deviation: 4.2708

statistical Analysis for 6 subject:
Mean: 65.0
Median: 65.0
Standard Deviation: 7.0711

statistical Analysis for 7 subject:
Mean: 82.6
Median: 82